param(
  [string]$ProjectName = "mscloud",
  [string]$EnvironmentName = "dev",
  [string]$Location = "southeastasia",
  [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Tao file cau hinh env.ps1 cho tat ca script deploy Azure.
# File nay gom ten resource, password PostgreSQL va danh sach service.
$envPath = Join-Path $PSScriptRoot "env.ps1"
if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
  throw "env.ps1 already exists. Use -Force to overwrite: $envPath"
}

# Ham nay lam sach ten resource de hop le voi rule cua Azure.
function Convert-ToAzureToken([string]$Value, [int]$MaxLength, [string]$Fallback) {
  $token = ($Value.ToLowerInvariant() -replace "[^a-z0-9]", "")
  if ([string]::IsNullOrWhiteSpace($token)) {
    $token = $Fallback
  }
  if ($token.Length -gt $MaxLength) {
    $token = $token.Substring(0, $MaxLength)
  }
  return $token
}

# Ham nay bien ten PostgreSQL thanh format hop le cho server name.
function Convert-ToPostgresToken([string]$Value, [int]$MaxLength, [string]$Fallback) {
  $token = ($Value.ToLowerInvariant() -replace "[^a-z0-9-]", "-").Trim("-")
  $token = $token -replace "-{2,}", "-"
  if ([string]::IsNullOrWhiteSpace($token)) {
    $token = $Fallback
  }
  if ($token.Length -gt $MaxLength) {
    $token = $token.Substring(0, $MaxLength).Trim("-")
  }
  return $token
}

# Tao chuoi ngau nhien de dung lam suffix ten resource va password.
function New-RandomString([int]$Length) {
  $alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  $bytes = [byte[]]::new($Length)
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }

  $chars = foreach ($byte in $bytes) {
    $alphabet[$byte % $alphabet.Length]
  }
  return -join $chars
}

$projectToken = Convert-ToAzureToken $ProjectName 20 "mscloud"
$environmentToken = Convert-ToAzureToken $EnvironmentName 8 "dev"
$postgresProjectToken = Convert-ToPostgresToken $ProjectName 24 "mscloud"
$postgresEnvironmentToken = Convert-ToPostgresToken $EnvironmentName 10 "dev"
$suffix = ([System.Guid]::NewGuid().ToString("N")).Substring(0, 6)
# Password dung cho PostgreSQL local/Azure test environment.
$postgresPassword = "$(New-RandomString 24)aA1!"

$acrName = "$($projectToken)acr$($environmentToken)$suffix"
$postgresServerName = "psql-$postgresProjectToken-$postgresEnvironmentToken-$suffix"

@"
# Generated by infra/azure/init-env.ps1.
# This file can contain secrets and is ignored by .gitignore.

`$ProjectName = "$ProjectName"
`$EnvironmentName = "$EnvironmentName"
`$Location = "$Location"

`$ResourceGroup = "rg-`$ProjectName-`$EnvironmentName"
`$ContainerAppsEnv = "cae-`$ProjectName-`$EnvironmentName"
`$LogAnalyticsWorkspace = "log-`$ProjectName-`$EnvironmentName"
`$UserAssignedIdentity = "id-`$ProjectName-`$EnvironmentName"

`$AcrName = "$acrName"

`$PostgresServerName = "$postgresServerName"
`$PostgresAdminUser = "mscloudadmin"
`$PostgresAdminPassword = "$postgresPassword"
`$PostgresSku = "Standard_B1ms"
`$PostgresTier = "Burstable"
`$PostgresVersion = "16"

`$ImageTag = "latest"

`$AuthEnabled = "false"
`$AuthIssuerUri = ""
`$AuthAudience = ""

`$Services = @(
  "user-service",
  "product-service",
  "notification-service",
  "order-service",
  "gateway-service"
)
"@ | Set-Content -LiteralPath $envPath -Encoding UTF8

Write-Host "Created $envPath"
Write-Host "Next: run infra/azure/test-preflight.ps1"
