param(
  # Tên project dùng để sinh tên resource Azure, ví dụ mscloud.
  [string]$ProjectName = "mscloud",
  # Tên môi trường deploy, ví dụ dev, staging, prod.
  [string]$EnvironmentName = "dev",
  # Azure region sẽ tạo resource.
  [string]$Location = "southeastasia",
  # Cho phép ghi đè env.ps1 nếu file đã tồn tại.
  [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Tạo file cấu hình env.ps1 cho toàn bộ script deploy Azure.
# File này có thể chứa secret nên phải được giữ local và không commit.
$envPath = Join-Path $PSScriptRoot "env.ps1"
if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
  throw "env.ps1 already exists. Use -Force to overwrite: $envPath"
}

# Chuẩn hóa tên resource theo rule của Azure: chỉ chữ thường và số.
function Convert-ToAzureToken([string]$Value, [int]$MaxLength, [string]$Fallback) {
  $token = ($Value.ToLowerInvariant() -replace "[^a-z0-9]", "")
  if ([string]::IsNullOrWhiteSpace($token)) {
    $token = $Fallback
  }
  if ($token.Length -gt $MaxLength) {
    $token = $token.Substring(0, $MaxLength)
  }
  return $token
}

# Chuẩn hóa tên PostgreSQL server: chữ thường, số và dấu gạch ngang.
function Convert-ToPostgresToken([string]$Value, [int]$MaxLength, [string]$Fallback) {
  $token = ($Value.ToLowerInvariant() -replace "[^a-z0-9-]", "-").Trim("-")
  $token = $token -replace "-{2,}", "-"
  if ([string]::IsNullOrWhiteSpace($token)) {
    $token = $Fallback
  }
  if ($token.Length -gt $MaxLength) {
    $token = $token.Substring(0, $MaxLength).Trim("-")
  }
  return $token
}

# Tạo chuỗi ngẫu nhiên để dùng làm suffix resource và password dev/test.
function New-RandomString([int]$Length) {
  $alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  $bytes = [byte[]]::new($Length)
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }

  $chars = foreach ($byte in $bytes) {
    $alphabet[$byte % $alphabet.Length]
  }
  return -join $chars
}

$projectToken = Convert-ToAzureToken $ProjectName 20 "mscloud"
$environmentToken = Convert-ToAzureToken $EnvironmentName 8 "dev"
$postgresProjectToken = Convert-ToPostgresToken $ProjectName 24 "mscloud"
$postgresEnvironmentToken = Convert-ToPostgresToken $EnvironmentName 10 "dev"

# Suffix giúp tránh trùng tên ACR/PostgreSQL vì các tên này phải unique toàn Azure.
$suffix = ([System.Guid]::NewGuid().ToString("N")).Substring(0, 6)

# Password dùng cho PostgreSQL dev/test; production nên chuyển sang Key Vault.
$postgresPassword = "$(New-RandomString 24)aA1!"

$acrName = "$($projectToken)acr$($environmentToken)$suffix"
$postgresServerName = "psql-$postgresProjectToken-$postgresEnvironmentToken-$suffix"

@"
# Generated by infra/azure/init-env.ps1.
# This file can contain secrets and is ignored by .gitignore.
# Các script deploy sẽ dot-source file này thông qua common.ps1/Import-DeployConfig.

`$ProjectName = "$ProjectName"
`$EnvironmentName = "$EnvironmentName"
`$Location = "$Location"

# ResourceGroup là "folder logic" gom toàn bộ resource Azure của project/môi trường.
`$ResourceGroup = "rg-`$ProjectName-`$EnvironmentName"

# ContainerAppsEnv là runtime chung cho các Azure Container Apps.
`$ContainerAppsEnv = "cae-`$ProjectName-`$EnvironmentName"

# Log Analytics nhận log của Container Apps để xem lỗi/runtime.
`$LogAnalyticsWorkspace = "log-`$ProjectName-`$EnvironmentName"

# Managed Identity cho phép Container Apps pull image từ ACR không cần lưu password.
`$UserAssignedIdentity = "id-`$ProjectName-`$EnvironmentName"

# ACR lưu Docker image của các service.
`$AcrName = "$acrName"

# PostgreSQL Flexible Server chứa các database user_db/product_db/order_db/notification_db.
`$PostgresServerName = "$postgresServerName"
`$PostgresAdminUser = "mscloudadmin"

# Password dev/test được sinh tự động; production nên đưa secret sang Key Vault.
`$PostgresAdminPassword = "$postgresPassword"
`$PostgresSku = "Standard_B1ms"
`$PostgresTier = "Burstable"
`$PostgresVersion = "16"

# Tag image sẽ được build/push/deploy.
`$ImageTag = "latest"

# Auth tắt mặc định. Khi tích hợp Entra External ID thì điền issuer/audience và đổi AuthEnabled=true.
`$AuthEnabled = "false"
`$AuthIssuerUri = ""
`$AuthAudience = ""

# Danh sách service hợp lệ để script build/deploy kiểm tra tránh nhập nhầm.
`$Services = @(
  "user-service",
  "product-service",
  "notification-service",
  "order-service",
  "gateway-service"
)
"@ | Set-Content -LiteralPath $envPath -Encoding UTF8

Write-Host "Created $envPath"
Write-Host "Next: run infra/azure/test-preflight.ps1"
